<a href="https://colab.research.google.com/github/shahdelsayed-ss/asse-2-sec3/blob/main/ass_sec_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
ages=np.array([18,21,20,19,22,23,21,22,19])

In [3]:
np.sum(ages)

np.int64(185)

In [5]:
np.size(ages)

9

In [7]:
mean1=np.sum(ages)/np.size(ages)
print(mean1)

20.555555555555557


In [8]:
np.mean(ages)

np.float64(20.555555555555557)

In [9]:
np.median(ages)

np.float64(21.0)

In [12]:
np.random.randint(10, 50, size=15)

array([13, 12, 18, 19, 24, 17, 37, 43, 46, 45, 29, 17, 36, 46, 34])

In [13]:
np.sort(np.random.randint(10, 50, size=15))

array([11, 18, 22, 28, 32, 34, 36, 37, 40, 41, 45, 45, 46, 47, 49])

In [14]:
np.median(np.sort(np.random.randint(10, 50, size=15)))

np.float64(35.0)

In [16]:
min=11
max=49
range=max-min
print(range)

38


In [20]:
min1=np.min(np.sort(np.random.randint(10, 50, size=15)))

In [21]:
max1=np.max(np.sort(np.random.randint(10, 50, size=15)))

In [22]:
range=max1-min1
print(range)

38


In [ ]:
data=np.array([5,7,3,7,9,10,15,7])

In [24]:
data=np.array([5,7,3,7,9,10,15,7])
np.var(data)

np.float64(11.359375)

In [25]:
np.std(data)

np.float64(3.370367190678191)

In [ ]:
data=np.array([5,7,3,7,9,10,15,7])

In [27]:
mean2=sum(data)/len(data)
print(mean2)

7.875


In [28]:
variance=sum((data-mean2)**2)/len(data)
print(variance)

11.359375


In [29]:
stander=variance**0.5
print(stander)

3.370367190678191


In [32]:
q1=np.percentile(data,25)
print(q1)
q2=np.percentile(data,50)
print(q2)
q3=np.percentile(data,75)
print(q3)

6.5
7.0
9.25


In [33]:
iqr=q3-q1
print(iqr)

2.75


In [34]:
z_scores=(data-np.mean(data))/np.std(data)
print(z_scores)

[-0.85302278 -0.25961563 -1.44642994 -0.25961563  0.33379152  0.6304951
  2.11401298 -0.25961563]


In [37]:
list2=np.random.randint(1, 100, size=20)
print(list2)

[22 31 61 89 98 42 48 60 30 58 74 53  6 22 34 71  2 18 62 58]


In [38]:
size=len(list2)
print(size)

20


In [39]:
z=np.ones(size)/size
print(z)

[0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05
 0.05 0.05 0.05 0.05 0.05 0.05]


In [40]:
w=np.convolve(list2,z,'valid')
print(w)

[46.95]


In [41]:
list3=np.random.randint(1, 50, size=25)
print(list3)

[11 15 20 26 37 39 49 35 22 48 14 10 10 39 13 33 35 15 10 30 23 31  8 22
 34]


In [44]:
list4=np.append(list3, [300,400])
print(list4)

[ 11  15  20  26  37  39  49  35  22  48  14  10  10  39  13  33  35  15
  10  30  23  31   8  22  34 300 400]


In [45]:
q1=np.percentile(list4,25)
print(q1)
q2=np.percentile(list4,50)
print(q2)
q3=np.percentile(list4,75)
print(q3)

14.5
26.0
36.0


In [46]:
IQR=q3-q1
print(IQR)

21.5
